### PR TITLE
bug: fix type of value in the case object

### PR DESCRIPTION
**Pull request by cshezi**
changing rule config case value type to string from number

### CODE REVIEW

**Review by Lenbkr — APPROVED** [review]
YOLO

**Review by rtkay123 — CHANGES_REQUESTED** [review]
Consider renaming to `cases` as per @Justus-Ortlepp-frms request https://github.com/frmscoe/frms-coe-lib/blob/19273ccd9d5b66a2cf1f3959992c7b3aa56b65e1/src/interfaces/rule/RuleConfig.ts#L15

**Comment by cshezi** [comment]
> Consider renaming to `cases` as per @Justus-Ortlepp-frms request
> 
> https://github.com/frmscoe/frms-coe-lib/blob/19273ccd9d5b66a2cf1f3959992c7b3aa56b65e1/src/interfaces/rule/RuleConfig.ts#L15

This will bring breaking changes to the rule-executor as all the rules deployed have got case check on the determine outcome function and not "cases" This will need executor changes, lets please move these changes to after release, as their changes need change both of rule dependant lib & rule-executor

**Comment by rtkay123** [comment]
> @rtkay123
> 
> > Consider renaming to `cases` as per @Justus-Ortlepp-frms request
> > https://github.com/frmscoe/frms-coe-lib/blob/19273ccd9d5b66a2cf1f3959992c7b3aa56b65e1/src/interfaces/rule/RuleConfig.ts#L15
> 
> This will bring breaking changes to the rule-executor as all the rules deployed have got case check on the determine outcome function and not "cases" This will need executor changes, lets please move these changes to after release, as their changes need change both of rule dependant lib & rule-executor

Changing the type of a field in a public interface (your PR) is already a breaking change

**Pull request closed without merging**
